### ISSUE TITLE
Consistent unhandled exception for shaders.

### ISSUE THREAD

**Issue by McCaffeteria** [TiredHobgoblin/Destiny-Collada-Generator#10] opened 2021-05-13 09:51 UTC
Downloading a shader using basically any version of the tool throws an unhandled exception:

DARE v1.5.2
DCG v1.7.4
Hashes: 1371145728
Calling item definition from manifest...
Unhandled exception.
System.NullReferenceException: Object reference not set to an instance of an object.
at DestinyColladaGenerator.apiSupport.convertByHash(String game, String[] hashes, String fileOut) in C:\Users\admin\Desktop\CSharpTGXMConverter\ApiSupport.cs:line 236
at DestinyColladaGenerator.Program.Main(String[] args) in C:\Users\admin\Desktop\CSharpTGXMConverter\Program.cs:line 66

Done (Exit Code: 3221225477)

I've tried with v1.7.4, v1.7.1, and v1.7.0 and they all seem to fail similarly. I don't recall there being any issues for shaders on the older 1.7._ versions in the past, so perhaps it's a change made to the database on Bungie's end? Downloading armor seems unchanged though.

**Comment by TiredHobgoblin** [comment] 2021-05-13 16:25
This is a new issue caused by some API changes with the new shader system. I'm currently in contact with someone at Bungie to get information on how to fix it, but for now shader items are completely non-functional.

**Comment by TiredHobgoblin** [comment] 2022-01-20 16:21
Finally got a fix for this, via integration with another tool that pulls shader data from the game files.

**Closed as completed by TiredHobgoblin** 2022-01-20 16:21 UTC
