### ISSUE TITLE
Wishlist 2020

### ISSUE THREAD

**Issue by TiredHobgoblin** [TiredHobgoblin/Destiny-Collada-Generator#4] opened 2020-02-25 02:10 UTC
Got an idea, or want something added? Stick it here! (It'll help me remember it.)
- [X] Shader presets/values
- [x] ~~Fix skeleton~~ (Seems to be an issue with Blender.)
- [X] List shaders used by an item *by name,* or add material slots.
- [x] Skip invalid hashes instead of crashing
- [X] Cancel conversion action if no valid hashes
- [x] Fix issue that causes some sets to crash when converted all at once
- [ ] Fix output files to be compatible with more than just Blender
- [X] Apply a default detail UV scaling

**Comment by vfxbroseph** [comment] 2020-03-13 14:04
Physics Object Detail Texture UVs:
Capes/Robes/Marks do not have an alternate set of UVs for detail maps, which can leave those areas noticably blank unless edited with the following steps. The problem is fixed by copying and renaming uv0 as uv1, then scaling up the contents of uv1 by 5x. In testing, using 5x size multiplication on both the Exile cloak and Exile robes yeilded the same results compared to the rest of the armor set's detail texture size.

**Closed as completed** 2022-02-08 19:13 UTC
